server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true
  spring:
    datasource:
      url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}
      driver-class-name: org.h2.Driver
      username: ${rds.username}
      password: ${rds.password}
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: none
      properties:
        '[hibernate.default.batch.fetch_size]': 100

logging:
  level:
      '[com.lyg.junitstudy]': INFO
